image: node:latest

cache:
  paths:
    - node_modules/

pipeline:
  only:
    - master
  environment:
    name: PROD
  script:
    - npm install --unsafe-perm
    - npm run fetch
    - npm run output:store

pipeline:
  only:
    - develop
  environment:
    name: INT
  script:
    - npm install --unsafe-perm
    - npm run fetch
    - npm run output:store