image: node:latest

before_script:
  - mkdir -p ~/.ssh && echo -e "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa && chmod og-rwx ~/.ssh/id_rsa
  - npm install --unsafe-perm

cache:
  paths:
    - node_modules/

pipeline_prod:
  only:
    - master
  environment:
    name: PROD
  script:
    - npm run fetch
    - npm run output:store

pipeline_int:
  only:
    - develop
  except:
    variables:
      - $RELEASE == "zazuko"
  environment:
    name: INT
  script:
    - ./scripts/main.sh
  #  - npm run fetch
  #  - npm run output:store

pipeline_test:
  only:
    variables:
      - $RELEASE == "zazuko"
  environment:
    name: TEST
  script:
    - npm run fetch
    - npm run output:store