image: zazukoians/node-java-jena
before_script:
  - apt-get update && apt-get install -y unzip
  - scripts/bootstrap.sh
  - npm install

# stages
stages:
- fetch
- convert
- post

# jobs

curl_hdb_job:
  stage: fetch
  tags: 
    - ssz
  script:
    - npm run get-hdb
  artifacts:
    paths:
      - input/hdb.csv
    expire_in: 30 minutes

curl_dimension_job:
  stage: fetch
  tags: 
    - ssz
  script:
    - npm run get-dimensions
  artifacts:
    paths:
      - input/HDB_Listen.xlsx
    expire_in: 30 minutes

convert_hdb_job:
  stage: convert
  tags: 
    - ssz
  script:
    - npm run convert-hdb
    - npm run clean-hdb
  artifacts:
    paths:
      - target/hdb-clean.nt
      - target/hdb-meta.nt
    expire_in: 1 day

convert_dimensions_job:
  stage: convert
  tags: 
    - ssz
  script:
    - npm run convert-dimensions
    - npm run clean-dimensions
  artifacts:
    paths:
      - target/dimensions.nt
    expire_in: 1 day

tdb_cleanup_job:
  stage: convert
  tags:
    - ssz
  script:
    - npm run void-timestamp
    - npm run tdb-load
    - npm run tdb-query
    - npm run tdb-dump
  artifacts:
    paths:
      - target/everything.nt
    expire_in: 1 day

post_test_job:
  stage: post
  tags: 
    - ssz
  only:
    - tags
#    - develop
  script:
    - npm run ssz-lindas

post_prod_job:
  stage: post
  tags: 
    - ssz
  only:
    - tags
  script:
    - npm run ssz-lindas # should be removed once we know it works properly
#    - npm run ssz-lindas-prod