image: zazukoians/node-java-jena
before_script:
  - scripts/bootstrap.sh
  - npm install

# stages
stages:
- fetch
- convert
- staging
- validate
- post

# jobs

curl_hdb_job:
  stage: fetch
  tags: 
    - ssz
  script:
    - npm run get-hdb
  artifacts:
    paths:
      - input/hdb.csv
      - input/hdb_mapping.csv
    expire_in: 30 minutes

curl_dimension_job:
  stage: fetch
  tags: 
    - ssz
  script:
    - npm run get-dimensions
  artifacts:
    paths:
      - input/HDB_Listen.xlsx
    expire_in: 30 minutes

convert_hdb_job:
  stage: convert
  tags: 
    - ssz
  script:
    - npm run convert-hdb
    - npm run clean-hdb
  artifacts:
    paths:
      - target/hdb-clean.nt
      - target/hdb-meta.nt
    expire_in: 1 day
  dependencies:
    - curl_hdb_job
  
convert_dimensions_job:
  stage: convert
  tags: 
    - ssz
  script:
    - npm run convert-dimensions
    - npm run clean-dimensions
  artifacts:
    paths:
      - target/dimensions.nt
    expire_in: 1 day
  dependencies:
    - curl_dimension_job

staging_tdb_job:
  stage: staging
  tags:
    - ssz
  script:
    - npm run void-timestamp
    - npm run tdb-load
    - npm run tdb-query
    - npm run tdb-dump
  artifacts:
    paths:
      - target/everything.nt
    expire_in: 1 day
  dependencies:
    - convert_dimensions_job
    - convert_hdb_job

validate_riot_job:
  stage: validate
  tags:
    - ssz
  script:
    - npm run validate-riot
  artifacts:
    paths:
      - target/everything.nt.gz
    expire_in: 1 day
  dependencies:
    - staging_tdb_job

post_test_job:
  stage: post
  tags: 
    - ssz
  only:
#    - tags
    - develop
  script:
    - npm run ssz-zazuko
  dependencies:
    - validate_riot_job

post_prod_job:
  stage: post
  tags: 
    - ssz
  only:
    - tags
  script:
    - npm run ssz-lindas-prod-s3
  dependencies:
    - validate_riot_job
