image: node:8.9
before_script:
  - apt-get update && apt-get install -y unzip
  - scripts/bootstrap.sh
  - npm install

#services:
# - postgres:9.5.0


# stages
stages:
- fetch
- convert
- post

# jobs

curl_hdb_job:
  stage: fetch
  tags: 
    - ssz
  script:
    - npm run get-hdb
  artifacts:
    paths:
      - input/hdb.csv
    expire_in: 30 minutes

curl_dimension_job:
  stage: fetch
  tags: 
    - ssz
  script:
    - npm run get-dimensions
  artifacts:
    paths:
      - input/HDB_Listen.xlsx
    expire_in: 30 minutes


## TODO split in two in JS

convert_job:
  stage: convert
  tags: 
    - ssz
  script:
    - npm run convert
    - npm run clean-dimensions
    - npm run clean-hdb
  artifacts:
    paths:
      - target/dimensions.nt
      - target/hdb-clean.nt
    expire_in: 1 day

post_test_job:
  stage: post
  tags: 
    - ssz
  only:
    - develop
  script:
    - npm run ssz-lindas

post_prod_job:
  stage: post
  tags: 
    - ssz
  only:
    - tags
  script:
    - npm run ssz-lindas # should be removed once we know it works properly
#    - npm run ssz-lindas-prod