image: node:latest

cache:
  paths:
    - node_modules/

pipeline_prod:
  only:
    - master
  environment:
    name: PROD
  script:
    - npm install --unsafe-perm
    - npm run fetch
    - npm run output:store

pipeline_int:
  only:
    - develop
  environment:
    name: INT
  script:
    - npm install --unsafe-perm
    - npm run fetch
    - npm run output:store

pipeline_test:
  only:
    - develop
  environment:
    name: TEST
  script:
    - npm install --unsafe-perm
    - npm run fetch
    - npm run output:store