image: node:latest

cache:
  paths:
    - node_modules/

pipeline:
  environment: # defines the environment used for variables
    name: PROD
  script:
    - npm install --unsafe-perm
    - env
    - npm run fetch
    - npm run output:store
#  artifacts:
#    paths:
#      - output/transformed.nt
