image: node:latest

cache:
  paths:
    - node_modules/

pipeline:
  environment: # defines the environment used for variables
    name: INT
  script:
    - npm install --unsafe-perm
    - npm run output:file
  artifacts:
    paths:
      - output/transformed.nt
