image: node:8.9
before_script:
  - scripts/bootstrap.sh

#services:
# - postgres:9.5.0

hdb_complete:
  script:
  - npm install
  - npm run build-local
  artifacts: 
    paths: 
      - target/dimensions.nt
      - target/hdb-clean.nt
      expire_in: 1 day
