default:
  image: docker.io/library/node:18

before_script:
  - mkdir -p ~/.ssh && echo -e "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa && chmod og-rwx ~/.ssh/id_rsa
#  - echo "$SSH_PRIVATE_KEY" | ssh-add - > /dev/null
  - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - npm ci
#  - git clone https://github.com/zazuko/ssz-views.git && cd ssz-views && npm install
  - cd $CI_PROJECT_DIR

cache:
  paths:
    - node_modules/

stages:
  - pipeline
  - metadata

pipeline_prod:
  stage: pipeline
  only:
    - master
#   - develop
  tags:
    - medium
  environment:
    name: PROD
  script:
    - ./scripts/main.sh

pipeline_int:
  stage: pipeline
  only:
    - develop
  tags:
    - medium
  except:
    variables:
      - $RELEASE == "zazuko"
  environment:
    name: INT
  script:
    - ./scripts/main.sh
#  artifacts:
#    paths:
#      - output/output.nt.gz
#    expire_in: 1 day

#pipeline_test:
#  only:
#    - develop
#    variables:
    #  - $RELEASE == "zazuko"
#  tags:
#    - medium
#  environment:
#    name: TEST
#  script:
#    - ./scripts/main.sh
#  artifacts:
#    paths:
#      - output/output.nt
#    expire_in: 1 day

metadata:
  stage: metadata
  environment:
    name: $CI_ENVIRONMENT_NAME
  script:
    - curl -LO https://github.com/Orange-OpenSource/hurl/releases/download/1.8.0/hurl_1.8.0_amd64.deb
    - apt update && apt install ./hurl_1.8.0_amd64.deb
    - hurl -V
